### ISSUE TITLE
[BUG] 无法将『御剑怜侍』拖动到副屏

### ISSUE THREAD

**Issue by Zxis233** [tiantian180/MilesEdgeworth#1]
『请看VCR。』

*Zxis233* 使用了证物 ***GIF***

![GIF 2024-6-7 20-05-56](https://github.com/tiantian180/MilesEdgeworth/assets/91776041/278aaad1-f5ec-45e3-8b9d-0c0aadca6288)

**Comment by Zxis233** [comment]
- OS: Windows11 Education Dev Channel 26120.751

**Comment by tiantian180** [comment]
新增了一个双屏版本（MilesEdgeworth_new.rar），另外还追加了快速晃动触发害怕地震的小动画。b站置顶评论里也贴了下载链接，可以试试看，要先右键设置双屏选项。不过可能还是有漏洞，因为我是win10且没有双屏，没办法测试效果orz 如果有问题的话还请及时反馈给我，谢谢！

**Comment by Zxis233** [comment]
话说其实可以发行release的，这样子看着更方便，不同版本间也易于大家选择 ^_^

**Comment by tiantian180** [comment]
> 话说其实可以发行release的，这样子看着更方便，不同版本间也易于大家选择 ^_^

不太熟悉GitHub不好意思哈哈哈，原来还有专门的release这一栏。已创建，谢谢你的提醒！

**Comment by Zxis233** [comment]
![67f451d420f25cef3099543357fa3739](https://github.com/tiantian180/MilesEdgeworth/assets/91776041/a73da88e-0b2b-4869-98e8-9710b52859ee)
